/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Guia7NiveisRouteImport } from './routes/guia-7-niveis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Guia7NiveisRoute = Guia7NiveisRouteImport.update({
  id: '/guia-7-niveis',
  path: '/guia-7-niveis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guia-7-niveis': typeof Guia7NiveisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guia-7-niveis': typeof Guia7NiveisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guia-7-niveis': typeof Guia7NiveisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guia-7-niveis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guia-7-niveis'
  id: '__root__' | '/' | '/guia-7-niveis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Guia7NiveisRoute: typeof Guia7NiveisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-7-niveis': {
      id: '/guia-7-niveis'
      path: '/guia-7-niveis'
      fullPath: '/guia-7-niveis'
      preLoaderRoute: typeof Guia7NiveisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Guia7NiveisRoute: Guia7NiveisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
